orbs:
  slack: circleci/slack@3.4.2
version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter test test/widget_test.dart
      - run: flutter -v build apk
