orbs:
  slack: circleci/slack@3.4.2
version: 2.1
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter doctor
      - run: flutter drive --target=./test_driver/app.dart
      - run: flutter -v build apk
