orbs:
  slack: circleci/slack@3.4.2
version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
      - image: circleci/android:api-26-alpha
    environment:
          JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-16;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-16;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait emulator
          command: |
            circle-android wait-for-boot
            sleep 30
            adb shell input keyevent 82
      - run: flutter pub get
      - run: flutter doctor
      - run: flutter devices
      - run: flutter drive --target=./test_driver/app.dart
      - run: flutter -v build apk