orbs:
  slack: circleci/slack@3.4.2
version: 2.1
commands:
  flutter_restore_cache:
    steps:
      - restore_cache:
          keys: flutter-cache-{{ .Branch }}
  flutter_save_cache:
    parameters:
      root_path:
        type: string
        default: "app"
    steps:
      - save_cache:
          key: flutter-cache-{{ .Branch }}
          paths:
            - "<< parameters.root_path >>/android/.gradle"
            - "<< parameters.root_path >>/android/gradle"
            - "<< parameters.root_path >>/build"
            - /opt/android-sdk-linux/
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter pub get
      - run: flutter doctor
      - flutter_restore_cache
      # buildしたapkを/tmpにコピー
      - run:
          working_directory: app
          command: |
            flutter -v build apk
            cp /home/cirrus/project/build/app/outputs/apk/release/app-release.apk /tmp
      - flutter_save_cache
      # /tmpのapp.apkを一時的に保存して、次のjobにわたす
      - persist_to_workspace:
          root: /tmp
          paths:
            - app.apk
#jobs:
#  build:
#    docker:
#      - image: cirrusci/flutter
#    steps:
#      - checkout
#      - run: flutter pub get
#      - run: flutter doctor
#      - run: flutter -v build ios

workflows:
  version: 2
  flutter:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/